# Extended Citadel Paint Database
# This file contains comprehensive paint data to be imported into the main server

CITADEL_EXTENDED_PAINTS = [
    # ========== CITADEL BASE PAINTS (Complete 57 paints) ==========
    {"brand": "Citadel", "name": "Barak-Nar Burgundy", "paint_type": "base", "hex_color": "#45222E", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Corvus Black", "paint_type": "base", "hex_color": "#171314", "category": "Black", "is_custom": False},
    {"brand": "Citadel", "name": "Daemonette Hide", "paint_type": "base", "hex_color": "#696684", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Death Korps Drab", "paint_type": "base", "hex_color": "#3D4539", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Deathworld Forest", "paint_type": "base", "hex_color": "#5B6732", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Gal Vorbak Red", "paint_type": "base", "hex_color": "#4B213C", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Grey Knights Steel", "paint_type": "base", "hex_color": "#465863", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Grey Seer", "paint_type": "base", "hex_color": "#A2A5A7", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Incubi Darkness", "paint_type": "base", "hex_color": "#0B474A", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Ionrach Skin", "paint_type": "base", "hex_color": "#D4C9B4", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Iron Hands Steel", "paint_type": "base", "hex_color": "#44423F", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Iron Warriors", "paint_type": "base", "hex_color": "#414141", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Jokaero Orange", "paint_type": "base", "hex_color": "#EE3823", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Lupercal Green", "paint_type": "base", "hex_color": "#002C2B", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Night Lords Blue", "paint_type": "base", "hex_color": "#002B5C", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Nocturne Green", "paint_type": "base", "hex_color": "#162A29", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Phoenician Purple", "paint_type": "base", "hex_color": "#440052", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Ratskin Flesh", "paint_type": "base", "hex_color": "#AD6B4C", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Rhinox Hide", "paint_type": "base", "hex_color": "#462F30", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Screaming Bell", "paint_type": "base", "hex_color": "#C56335", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Steel Legion Drab", "paint_type": "base", "hex_color": "#5E5134", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Stegadon Scale Green", "paint_type": "base", "hex_color": "#074863", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "The Fang", "paint_type": "base", "hex_color": "#405B71", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Waaagh! Flesh", "paint_type": "base", "hex_color": "#1F5429", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Warplock Bronze", "paint_type": "base", "hex_color": "#654741", "category": "Metallic", "is_custom": False},
    
    # ========== CITADEL LAYER PAINTS (Extended) ==========
    {"brand": "Citadel", "name": "Ahriman Blue", "paint_type": "layer", "hex_color": "#1F8C9C", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Altdorf Guard Blue", "paint_type": "layer", "hex_color": "#1F56A7", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Baharroth Blue", "paint_type": "layer", "hex_color": "#58C1CD", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Balor Brown", "paint_type": "layer", "hex_color": "#8B5910", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Baneblade Brown", "paint_type": "layer", "hex_color": "#937F6D", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Bestigor Flesh", "paint_type": "layer", "hex_color": "#D38A57", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Blue Horror", "paint_type": "layer", "hex_color": "#A2BAD2", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Brass Scorpion", "paint_type": "layer", "hex_color": "#B7885F", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Dark Reaper", "paint_type": "layer", "hex_color": "#3B5150", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Dawnstone", "paint_type": "layer", "hex_color": "#70756E", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Deathclaw Brown", "paint_type": "layer", "hex_color": "#B36853", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Dechala Lilac", "paint_type": "layer", "hex_color": "#B598C9", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Deepkin Flesh", "paint_type": "layer", "hex_color": "#A8C5B8", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Doombull Brown", "paint_type": "layer", "hex_color": "#5D0009", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Dorn Yellow", "paint_type": "layer", "hex_color": "#FFF55A", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Elysian Green", "paint_type": "layer", "hex_color": "#6B8C23", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Emperor's Children", "paint_type": "layer", "hex_color": "#B94278", "category": "Pink", "is_custom": False},
    {"brand": "Citadel", "name": "Eshin Grey", "paint_type": "layer", "hex_color": "#484B4E", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Flayed One Flesh", "paint_type": "layer", "hex_color": "#ECC083", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Fulgrim Pink", "paint_type": "layer", "hex_color": "#F4AFD7", "category": "Pink", "is_custom": False},
    {"brand": "Citadel", "name": "Fulgurite Copper", "paint_type": "layer", "hex_color": "#D88C57", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Gauss Blaster Green", "paint_type": "layer", "hex_color": "#80C1A3", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Gehenna's Gold", "paint_type": "layer", "hex_color": "#C1843D", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Genestealer Purple", "paint_type": "layer", "hex_color": "#7658A5", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Gorthor Brown", "paint_type": "layer", "hex_color": "#654741", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Hashut Copper", "paint_type": "layer", "hex_color": "#B56B4B", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Hoeth Blue", "paint_type": "layer", "hex_color": "#57A9D4", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Ironbreaker", "paint_type": "layer", "hex_color": "#A1A6A9", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Kabalite Green", "paint_type": "layer", "hex_color": "#038C67", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Karak Stone", "paint_type": "layer", "hex_color": "#B7945C", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Knight-Questor Flesh", "paint_type": "layer", "hex_color": "#D7A86E", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Krieg Khaki", "paint_type": "layer", "hex_color": "#BEB695", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Loren Forest", "paint_type": "layer", "hex_color": "#50652B", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Lugganath Orange", "paint_type": "layer", "hex_color": "#F69B82", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Moot Green", "paint_type": "layer", "hex_color": "#3DAF44", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Nurgling Green", "paint_type": "layer", "hex_color": "#849C63", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Ogryn Camo", "paint_type": "layer", "hex_color": "#9DA94B", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Pink Horror", "paint_type": "layer", "hex_color": "#8E2757", "category": "Pink", "is_custom": False},
    {"brand": "Citadel", "name": "Phalanx Yellow", "paint_type": "layer", "hex_color": "#FFE200", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Runelord Brass", "paint_type": "layer", "hex_color": "#B5B090", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Russ Grey", "paint_type": "layer", "hex_color": "#507085", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Skarsnik Green", "paint_type": "layer", "hex_color": "#5F9370", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Skavenblight Dinge", "paint_type": "layer", "hex_color": "#47413B", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Skrag Brown", "paint_type": "layer", "hex_color": "#904E08", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Skullcrusher Brass", "paint_type": "layer", "hex_color": "#B88C4A", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Slaanesh Grey", "paint_type": "layer", "hex_color": "#DBD5E6", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Sotek Green", "paint_type": "layer", "hex_color": "#0B6974", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Squig Orange", "paint_type": "layer", "hex_color": "#AA4F44", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Stormvermin Fur", "paint_type": "layer", "hex_color": "#6D6A65", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Straken Green", "paint_type": "layer", "hex_color": "#628126", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Sybarite Green", "paint_type": "layer", "hex_color": "#1A9D7B", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Sycorax Bronze", "paint_type": "layer", "hex_color": "#C9A058", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Tallarn Sand", "paint_type": "layer", "hex_color": "#A67610", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Tau Light Ochre", "paint_type": "layer", "hex_color": "#BC6B10", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Teclis Blue", "paint_type": "layer", "hex_color": "#317EC1", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Temple Guard Blue", "paint_type": "layer", "hex_color": "#239489", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Thunderhawk Blue", "paint_type": "layer", "hex_color": "#417074", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Troll Slayer Orange", "paint_type": "layer", "hex_color": "#F36D2D", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Tuskgor Fur", "paint_type": "layer", "hex_color": "#863231", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Ulthuan Grey", "paint_type": "layer", "hex_color": "#C7E0D9", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Ungor Flesh", "paint_type": "layer", "hex_color": "#D6A766", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Warboss Green", "paint_type": "layer", "hex_color": "#3E805D", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Warpfiend Grey", "paint_type": "layer", "hex_color": "#6B6A74", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Wazdakka Red", "paint_type": "layer", "hex_color": "#8C0A0C", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Word Bearers Red", "paint_type": "layer", "hex_color": "#620104", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Xereus Purple", "paint_type": "layer", "hex_color": "#4B2B5A", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Zamesi Desert", "paint_type": "layer", "hex_color": "#D5A13B", "category": "Brown", "is_custom": False},
    
    # ========== CITADEL SHADE PAINTS (Extended) ==========
    {"brand": "Citadel", "name": "Agrax Earthshade Gloss", "paint_type": "shade", "hex_color": "#5A3D28", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Athonian Camoshade", "paint_type": "shade", "hex_color": "#2E3611", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Casandora Yellow", "paint_type": "shade", "hex_color": "#F4A512", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Coelia Greenshade", "paint_type": "shade", "hex_color": "#0E4D4D", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Nuln Oil Gloss", "paint_type": "shade", "hex_color": "#14100E", "category": "Black", "is_custom": False},
    {"brand": "Citadel", "name": "Reikland Fleshshade Gloss", "paint_type": "shade", "hex_color": "#5A2E28", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Soulblight Grey", "paint_type": "shade", "hex_color": "#444546", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Targor Rageshade", "paint_type": "shade", "hex_color": "#6D1919", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Tyran Blue", "paint_type": "shade", "hex_color": "#0D2B45", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Mortarion Grime", "paint_type": "shade", "hex_color": "#4A4828", "category": "Green", "is_custom": False},
    
    # ========== CITADEL CONTRAST PAINTS (Extended - 61 total) ==========
    {"brand": "Citadel", "name": "Aethermatic Blue", "paint_type": "contrast", "hex_color": "#7EC8E3", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Aggaros Dunes", "paint_type": "contrast", "hex_color": "#D4B896", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Akhelian Green", "paint_type": "contrast", "hex_color": "#3EB489", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Asurmen Blue", "paint_type": "contrast", "hex_color": "#2B4B7C", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Baal Red", "paint_type": "contrast", "hex_color": "#9A1115", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Bad Moon Yellow", "paint_type": "contrast", "hex_color": "#FFD900", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Basilicanum Grey", "paint_type": "contrast", "hex_color": "#5A5A5A", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Black Legion", "paint_type": "contrast", "hex_color": "#0D0D0D", "category": "Black", "is_custom": False},
    {"brand": "Citadel", "name": "Briar Queen Chill", "paint_type": "contrast", "hex_color": "#6CBAD8", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Celestium Blue", "paint_type": "contrast", "hex_color": "#4A90D9", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Creed Camo", "paint_type": "contrast", "hex_color": "#5C6B36", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Darkoath Flesh", "paint_type": "contrast", "hex_color": "#C9956D", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Doomfire Magenta", "paint_type": "contrast", "hex_color": "#9A2064", "category": "Pink", "is_custom": False},
    {"brand": "Citadel", "name": "Dreadful Visage", "paint_type": "contrast", "hex_color": "#5A456E", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Frostheart", "paint_type": "contrast", "hex_color": "#6DD3CE", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Fyreslayer Flesh", "paint_type": "contrast", "hex_color": "#D69B73", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Garaghak's Sewer", "paint_type": "contrast", "hex_color": "#5C4A32", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Gore-grunta Fur", "paint_type": "contrast", "hex_color": "#6B3A23", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Gryph-hound Orange", "paint_type": "contrast", "hex_color": "#E55137", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Gutrippa Flesh", "paint_type": "contrast", "hex_color": "#7B9E5E", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Hexwraith Flame", "paint_type": "contrast", "hex_color": "#6FCBA9", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Imperial Fist", "paint_type": "contrast", "hex_color": "#FFD41F", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Ironjawz Yellow", "paint_type": "contrast", "hex_color": "#FFD41F", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Karandras Green", "paint_type": "contrast", "hex_color": "#2E5339", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Kroxigor Scales", "paint_type": "contrast", "hex_color": "#148793", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Leviathan Purple", "paint_type": "contrast", "hex_color": "#4C3B5C", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Luxion Purple", "paint_type": "contrast", "hex_color": "#6B3FA0", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Magmadroth Flame", "paint_type": "contrast", "hex_color": "#F4874E", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Magos Purple", "paint_type": "contrast", "hex_color": "#6B3FA0", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Mantis Warrior Green", "paint_type": "contrast", "hex_color": "#5B8C45", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Militarum Green", "paint_type": "contrast", "hex_color": "#4A5A3C", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Nighthaunt Gloom", "paint_type": "contrast", "hex_color": "#5A9C9E", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Ork Flesh", "paint_type": "contrast", "hex_color": "#5B8035", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Pylar Glacier", "paint_type": "contrast", "hex_color": "#7EC8E3", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Ratling Grime", "paint_type": "contrast", "hex_color": "#5C4A32", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Sigvald Burgundy", "paint_type": "contrast", "hex_color": "#6B1F2F", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Space Wolves Grey", "paint_type": "contrast", "hex_color": "#7B8B9B", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Stormfiend", "paint_type": "contrast", "hex_color": "#3A6B8C", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Striking Scorpion Green", "paint_type": "contrast", "hex_color": "#5DAC4D", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Terradon Turquoise", "paint_type": "contrast", "hex_color": "#1A9D7B", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Aeldari Emerald", "paint_type": "contrast", "hex_color": "#1E7331", "category": "Green", "is_custom": False},
    
    # ========== CITADEL DRY PAINTS ==========
    {"brand": "Citadel", "name": "Astorath Red", "paint_type": "dry", "hex_color": "#DD482B", "category": "Red", "is_custom": False},
    {"brand": "Citadel", "name": "Changeling Pink", "paint_type": "dry", "hex_color": "#E5C5C6", "category": "Pink", "is_custom": False},
    {"brand": "Citadel", "name": "Chronus Blue", "paint_type": "dry", "hex_color": "#78B9D0", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Dawnstone (Dry)", "paint_type": "dry", "hex_color": "#70756E", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Eldar Flesh", "paint_type": "dry", "hex_color": "#C2917D", "category": "Flesh", "is_custom": False},
    {"brand": "Citadel", "name": "Etherium Blue", "paint_type": "dry", "hex_color": "#9EB5CE", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Golden Griffon", "paint_type": "dry", "hex_color": "#D3A936", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Golgfag Brown", "paint_type": "dry", "hex_color": "#6B3A23", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Hellion Green", "paint_type": "dry", "hex_color": "#7FC1A5", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Hexos Palesun", "paint_type": "dry", "hex_color": "#FFF36B", "category": "Yellow", "is_custom": False},
    {"brand": "Citadel", "name": "Hoeth Blue (Dry)", "paint_type": "dry", "hex_color": "#57A9D4", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Imrik Blue", "paint_type": "dry", "hex_color": "#3D8EC4", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Kindleflame", "paint_type": "dry", "hex_color": "#F79E86", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Longbeard Grey", "paint_type": "dry", "hex_color": "#CECEBD", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Lucius Lilac", "paint_type": "dry", "hex_color": "#B598C9", "category": "Purple", "is_custom": False},
    {"brand": "Citadel", "name": "Necron Compound", "paint_type": "dry", "hex_color": "#828B8E", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Niblet Green", "paint_type": "dry", "hex_color": "#378534", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Nurgling Green (Dry)", "paint_type": "dry", "hex_color": "#849C63", "category": "Green", "is_custom": False},
    {"brand": "Citadel", "name": "Praxeti White", "paint_type": "dry", "hex_color": "#FFFFFF", "category": "White", "is_custom": False},
    {"brand": "Citadel", "name": "Ryza Rust", "paint_type": "dry", "hex_color": "#EC6E30", "category": "Orange", "is_custom": False},
    {"brand": "Citadel", "name": "Sigmarite", "paint_type": "dry", "hex_color": "#CAAA51", "category": "Metallic", "is_custom": False},
    {"brand": "Citadel", "name": "Skink Blue", "paint_type": "dry", "hex_color": "#58AFD7", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Slaanesh Grey (Dry)", "paint_type": "dry", "hex_color": "#DBD5E6", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Stormfang", "paint_type": "dry", "hex_color": "#5F7F8E", "category": "Grey", "is_custom": False},
    {"brand": "Citadel", "name": "Sylvaneth Bark", "paint_type": "dry", "hex_color": "#4E4B48", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Terminatus Stone", "paint_type": "dry", "hex_color": "#BFB79E", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Thunderhawk Blue (Dry)", "paint_type": "dry", "hex_color": "#417074", "category": "Blue", "is_custom": False},
    {"brand": "Citadel", "name": "Tyrant Skull", "paint_type": "dry", "hex_color": "#CBC5AE", "category": "Bone", "is_custom": False},
    {"brand": "Citadel", "name": "Underhive Ash", "paint_type": "dry", "hex_color": "#B8B5A7", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Verminlord Hide", "paint_type": "dry", "hex_color": "#805247", "category": "Brown", "is_custom": False},
    {"brand": "Citadel", "name": "Wrack White", "paint_type": "dry", "hex_color": "#EEECE6", "category": "White", "is_custom": False},
    
    # ========== CITADEL TECHNICAL PAINTS ==========
    {"brand": "Citadel", "name": "Ardcoat", "paint_type": "technical", "hex_color": "#FFFFFF", "category": "Clear", "is_custom": False},
    {"brand": "Citadel", "name": "Astrogranite", "paint_type": "technical", "hex_color": "#7A7F7E", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Astrogranite Debris", "paint_type": "technical", "hex_color": "#636766", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Blood for the Blood God", "paint_type": "technical", "hex_color": "#7A0001", "category": "Effect", "is_custom": False},
    {"brand": "Citadel", "name": "Lahmian Medium", "paint_type": "technical", "hex_color": "#FFFFFF", "category": "Medium", "is_custom": False},
    {"brand": "Citadel", "name": "Martian Ironcrust", "paint_type": "technical", "hex_color": "#B56535", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Martian Ironearth", "paint_type": "technical", "hex_color": "#C35835", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Nihilakh Oxide", "paint_type": "technical", "hex_color": "#6BBDAB", "category": "Effect", "is_custom": False},
    {"brand": "Citadel", "name": "Nurgle's Rot", "paint_type": "technical", "hex_color": "#9B8F22", "category": "Effect", "is_custom": False},
    {"brand": "Citadel", "name": "Soulstone Blue", "paint_type": "technical", "hex_color": "#0064B5", "category": "Gem", "is_custom": False},
    {"brand": "Citadel", "name": "Spiritstone Red", "paint_type": "technical", "hex_color": "#AA0808", "category": "Gem", "is_custom": False},
    {"brand": "Citadel", "name": "Stirland Battlemire", "paint_type": "technical", "hex_color": "#4A3A2A", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Stirland Mud", "paint_type": "technical", "hex_color": "#483127", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Tesseract Glow", "paint_type": "technical", "hex_color": "#80C342", "category": "Effect", "is_custom": False},
    {"brand": "Citadel", "name": "Typhus Corrosion", "paint_type": "technical", "hex_color": "#473B2B", "category": "Effect", "is_custom": False},
    {"brand": "Citadel", "name": "Valhallan Blizzard", "paint_type": "technical", "hex_color": "#FFFFFF", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Waystone Green", "paint_type": "technical", "hex_color": "#00B055", "category": "Gem", "is_custom": False},
    {"brand": "Citadel", "name": "Agrellan Badland", "paint_type": "technical", "hex_color": "#D4B896", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Agrellan Earth", "paint_type": "technical", "hex_color": "#9B8044", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Armageddon Dust", "paint_type": "technical", "hex_color": "#D4B896", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Armageddon Dunes", "paint_type": "technical", "hex_color": "#B8A37D", "category": "Texture", "is_custom": False},
    {"brand": "Citadel", "name": "Mordant Earth", "paint_type": "technical", "hex_color": "#171412", "category": "Texture", "is_custom": False},
]
