# Comprehensive Miniature Paint Database
# Contains expanded paint data for Vallejo, Army Painter, Scale75, Reaper, and P3

VALLEJO_MODEL_COLOR = [
    # ========== VALLEJO MODEL COLOR (Complete - 150+ paints) ==========
    # Whites & Creams
    {"brand": "Vallejo Model Color", "name": "White", "paint_type": "base", "hex_color": "#FFFFFF", "category": "White", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Offwhite", "paint_type": "base", "hex_color": "#EFEEE2", "category": "White", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Ivory", "paint_type": "base", "hex_color": "#EFF1D9", "category": "White", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "White Grey", "paint_type": "base", "hex_color": "#EEF1EC", "category": "White", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Buff", "paint_type": "base", "hex_color": "#D2CA9F", "category": "Bone", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Pale Sand", "paint_type": "base", "hex_color": "#D1C49C", "category": "Bone", "is_custom": False},
    
    # Blacks & Greys
    {"brand": "Vallejo Model Color", "name": "Black", "paint_type": "base", "hex_color": "#252B31", "category": "Black", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Glossy Black", "paint_type": "base", "hex_color": "#010101", "category": "Black", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Black Grey", "paint_type": "base", "hex_color": "#2D373A", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "German Grey", "paint_type": "base", "hex_color": "#192F30", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Grey", "paint_type": "base", "hex_color": "#233E3D", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Neutral Grey", "paint_type": "base", "hex_color": "#64767A", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Medium Grey", "paint_type": "base", "hex_color": "#909B85", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Grey", "paint_type": "base", "hex_color": "#949C9A", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Sky Grey", "paint_type": "base", "hex_color": "#B3B6B2", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Silver Grey", "paint_type": "base", "hex_color": "#D8DFD5", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Stone Grey", "paint_type": "base", "hex_color": "#959980", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Basalt Grey", "paint_type": "base", "hex_color": "#576860", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "London Grey", "paint_type": "base", "hex_color": "#4A555E", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Grey Green", "paint_type": "base", "hex_color": "#565A60", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Green Grey", "paint_type": "base", "hex_color": "#827E61", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Blue Grey Pale", "paint_type": "base", "hex_color": "#9EA7A5", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Sea Grey", "paint_type": "base", "hex_color": "#787D7A", "category": "Grey", "is_custom": False},
    
    # Reds
    {"brand": "Vallejo Model Color", "name": "Flat Red", "paint_type": "base", "hex_color": "#AA3037", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Scarlet", "paint_type": "base", "hex_color": "#DA3630", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Vermillion", "paint_type": "base", "hex_color": "#D22B2D", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Carmine Red", "paint_type": "base", "hex_color": "#B73035", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Red", "paint_type": "base", "hex_color": "#A24A46", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Red", "paint_type": "base", "hex_color": "#91323A", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Amaranth Red", "paint_type": "base", "hex_color": "#CC4338", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Sunset Red", "paint_type": "base", "hex_color": "#C22C5F", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Violet Red", "paint_type": "base", "hex_color": "#6B2946", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Black Red", "paint_type": "base", "hex_color": "#5F2E39", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Burnt Cadmium Red", "paint_type": "base", "hex_color": "#623535", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Red Leather", "paint_type": "base", "hex_color": "#93453D", "category": "Red", "is_custom": False},
    
    # Oranges
    {"brand": "Vallejo Model Color", "name": "Orange Red", "paint_type": "base", "hex_color": "#E34C26", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Bright Orange", "paint_type": "base", "hex_color": "#F26833", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Orange", "paint_type": "base", "hex_color": "#F68627", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "German Orange", "paint_type": "base", "hex_color": "#F05426", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Clear Orange", "paint_type": "base", "hex_color": "#F1552C", "category": "Orange", "is_custom": False},
    
    # Yellows
    {"brand": "Vallejo Model Color", "name": "Flat Yellow", "paint_type": "base", "hex_color": "#FFCD25", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Deep Yellow", "paint_type": "base", "hex_color": "#FFE30C", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Golden Yellow", "paint_type": "base", "hex_color": "#F7C65E", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Yellow", "paint_type": "base", "hex_color": "#F7EA62", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Lemon Yellow", "paint_type": "base", "hex_color": "#FEF10E", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Ice Yellow", "paint_type": "base", "hex_color": "#FEEF87", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "German Yellow", "paint_type": "base", "hex_color": "#E8E589", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Sand Yellow", "paint_type": "base", "hex_color": "#D7BF75", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Yellow", "paint_type": "base", "hex_color": "#9D9059", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Yellow Green", "paint_type": "base", "hex_color": "#D9E02A", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Yellow Ochre", "paint_type": "base", "hex_color": "#C19448", "category": "Yellow", "is_custom": False},
    
    # Browns
    {"brand": "Vallejo Model Color", "name": "Flat Brown", "paint_type": "base", "hex_color": "#764841", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Brown", "paint_type": "base", "hex_color": "#BF764E", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Flat Earth", "paint_type": "base", "hex_color": "#87643C", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Burnt Umber", "paint_type": "base", "hex_color": "#665148", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Saddle Brown", "paint_type": "base", "hex_color": "#89584F", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Cavalry Brown", "paint_type": "base", "hex_color": "#853F3D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Mahogany Brown", "paint_type": "base", "hex_color": "#804B47", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Chocolate Brown", "paint_type": "base", "hex_color": "#5F5047", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Leather Brown", "paint_type": "base", "hex_color": "#4A4639", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Hull Red", "paint_type": "base", "hex_color": "#522724", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Cork Brown", "paint_type": "base", "hex_color": "#A57B63", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Brown Sand", "paint_type": "base", "hex_color": "#B08064", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Orange Brown", "paint_type": "base", "hex_color": "#B86F44", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Gold Brown", "paint_type": "base", "hex_color": "#BA8636", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Ochre Brown", "paint_type": "base", "hex_color": "#A77237", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Green Brown", "paint_type": "base", "hex_color": "#8D7B55", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Beige Brown", "paint_type": "base", "hex_color": "#78584A", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Tan Earth", "paint_type": "base", "hex_color": "#9C7962", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Green Ochre", "paint_type": "base", "hex_color": "#A98969", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Tan Yellow", "paint_type": "base", "hex_color": "#B5915D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Desert Yellow", "paint_type": "base", "hex_color": "#B19151", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Iraqi Sand", "paint_type": "base", "hex_color": "#B89972", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Sand", "paint_type": "base", "hex_color": "#D1B47E", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Khaki", "paint_type": "base", "hex_color": "#969163", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Khaki Grey", "paint_type": "base", "hex_color": "#8B7F5D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "US Field Drab", "paint_type": "base", "hex_color": "#705D43", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Deck Tan", "paint_type": "base", "hex_color": "#BEC5B3", "category": "Brown", "is_custom": False},
    
    # Greens
    {"brand": "Vallejo Model Color", "name": "Flat Green", "paint_type": "base", "hex_color": "#2A6531", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Green", "paint_type": "base", "hex_color": "#00A850", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Deep Green", "paint_type": "base", "hex_color": "#0A6B48", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Park Green Flat", "paint_type": "base", "hex_color": "#008C5D", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Emerald", "paint_type": "base", "hex_color": "#00906A", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Lime Green", "paint_type": "base", "hex_color": "#6FAE4E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Olive Green", "paint_type": "base", "hex_color": "#6A8B3A", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Golden Olive", "paint_type": "base", "hex_color": "#78923B", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Medium Olive", "paint_type": "base", "hex_color": "#226B2E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Yellow Olive", "paint_type": "base", "hex_color": "#26392E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Reflective Green", "paint_type": "base", "hex_color": "#496244", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Intermediate Green", "paint_type": "base", "hex_color": "#49944F", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Pastel Green", "paint_type": "base", "hex_color": "#A4BB99", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Green Sky", "paint_type": "base", "hex_color": "#59AD84", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Military Green", "paint_type": "base", "hex_color": "#3E5848", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Uniform Green", "paint_type": "base", "hex_color": "#577A38", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Black Green", "paint_type": "base", "hex_color": "#19423E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Olive Grey", "paint_type": "base", "hex_color": "#39584F", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Brown Violet", "paint_type": "base", "hex_color": "#4E5D4D", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "USA Olive Drab", "paint_type": "base", "hex_color": "#3B4947", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Gunship Green", "paint_type": "base", "hex_color": "#3D685E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Sea Green", "paint_type": "base", "hex_color": "#2F4844", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Bronce Green", "paint_type": "base", "hex_color": "#2A534F", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "German Uniform", "paint_type": "base", "hex_color": "#286254", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "US Dark Green", "paint_type": "base", "hex_color": "#5B6955", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Cam. Olive Green", "paint_type": "base", "hex_color": "#3C5549", "category": "Green", "is_custom": False},
    
    # Blues
    {"brand": "Vallejo Model Color", "name": "Blue", "paint_type": "base", "hex_color": "#043667", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Blue", "paint_type": "base", "hex_color": "#0D5A86", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Flat Blue", "paint_type": "base", "hex_color": "#336991", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Medium Blue", "paint_type": "base", "hex_color": "#066588", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Field Blue", "paint_type": "base", "hex_color": "#436872", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Prussian Blue", "paint_type": "base", "hex_color": "#2A546E", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Prussian Blue", "paint_type": "base", "hex_color": "#192C43", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Oxford Blue", "paint_type": "base", "hex_color": "#3A465F", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Royal Blue", "paint_type": "base", "hex_color": "#41558D", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Ultramarine", "paint_type": "base", "hex_color": "#3B5DA7", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Sky Blue", "paint_type": "base", "hex_color": "#86D6F7", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Deep Sky Blue", "paint_type": "base", "hex_color": "#00A6DA", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Andrea Blue", "paint_type": "base", "hex_color": "#008DC9", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Turquoise", "paint_type": "base", "hex_color": "#008E9C", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Turquoise", "paint_type": "base", "hex_color": "#0094A5", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Blue Green", "paint_type": "base", "hex_color": "#1A9496", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Grey Blue", "paint_type": "base", "hex_color": "#45708D", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Pastel Blue", "paint_type": "base", "hex_color": "#67859B", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Azure", "paint_type": "base", "hex_color": "#717CAD", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Intermediate Blue", "paint_type": "base", "hex_color": "#607A80", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Blue Grey", "paint_type": "base", "hex_color": "#5C7476", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Sea Blue", "paint_type": "base", "hex_color": "#2A4048", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "French Mirage Blue", "paint_type": "base", "hex_color": "#557880", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Pale Blue", "paint_type": "base", "hex_color": "#83B5B2", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Pale Grey Blue", "paint_type": "base", "hex_color": "#BACDD0", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Sea Grey", "paint_type": "base", "hex_color": "#97B4B5", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Green Blue", "paint_type": "base", "hex_color": "#6D9A95", "category": "Blue", "is_custom": False},
    
    # Purples
    {"brand": "Vallejo Model Color", "name": "Violet", "paint_type": "base", "hex_color": "#4B2F65", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Royal Purple", "paint_type": "base", "hex_color": "#4B2967", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Blue Violet", "paint_type": "base", "hex_color": "#795C9A", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Purple", "paint_type": "base", "hex_color": "#834A6C", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Magenta", "paint_type": "base", "hex_color": "#A92A56", "category": "Purple", "is_custom": False},
    
    # Pinks
    {"brand": "Vallejo Model Color", "name": "Pink", "paint_type": "base", "hex_color": "#D37497", "category": "Pink", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Old Rose", "paint_type": "base", "hex_color": "#D47B7D", "category": "Pink", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Salmon Rose", "paint_type": "base", "hex_color": "#F89D87", "category": "Pink", "is_custom": False},
    
    # Flesh Tones
    {"brand": "Vallejo Model Color", "name": "Basic Skintone", "paint_type": "base", "hex_color": "#FBBC8C", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Sunny Skintone", "paint_type": "base", "hex_color": "#F4B171", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Flat Flesh", "paint_type": "base", "hex_color": "#D8A977", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Dark Flesh", "paint_type": "base", "hex_color": "#D9A262", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Light Flesh", "paint_type": "base", "hex_color": "#FEEDD0", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Medium Fleshtone", "paint_type": "base", "hex_color": "#C08245", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Brown Rose", "paint_type": "base", "hex_color": "#CF8774", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Beige Red", "paint_type": "base", "hex_color": "#C79166", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Beige", "paint_type": "base", "hex_color": "#DBC58E", "category": "Flesh", "is_custom": False},
    
    # Metallics
    {"brand": "Vallejo Model Color", "name": "Gold", "paint_type": "metallic", "hex_color": "#D4AF37", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Silver", "paint_type": "metallic", "hex_color": "#C0C0C0", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Gunmetal Grey", "paint_type": "metallic", "hex_color": "#4A4D4E", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Bronze", "paint_type": "metallic", "hex_color": "#8C6239", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Copper", "paint_type": "metallic", "hex_color": "#B87333", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Old Gold", "paint_type": "metallic", "hex_color": "#CFB53B", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Brass", "paint_type": "metallic", "hex_color": "#B5A642", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Natural Steel", "paint_type": "metallic", "hex_color": "#888888", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Model Color", "name": "Oily Steel", "paint_type": "metallic", "hex_color": "#555555", "category": "Metallic", "is_custom": False},
]

VALLEJO_GAME_COLOR = [
    # ========== VALLEJO GAME COLOR (80+ paints) ==========
    {"brand": "Vallejo Game Color", "name": "Dead White", "paint_type": "base", "hex_color": "#FFFFFF", "category": "White", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Offwhite", "paint_type": "base", "hex_color": "#F5F4DA", "category": "White", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Bone White", "paint_type": "base", "hex_color": "#E8BE86", "category": "Bone", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Elfic Flesh", "paint_type": "base", "hex_color": "#CDC29C", "category": "Bone", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Black", "paint_type": "base", "hex_color": "#000000", "category": "Black", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Charcoal", "paint_type": "base", "hex_color": "#1C2E2E", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Charred Brown", "paint_type": "base", "hex_color": "#39343B", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Cold Grey", "paint_type": "base", "hex_color": "#54646D", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Sombre Grey", "paint_type": "base", "hex_color": "#4C5C7D", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Grey", "paint_type": "base", "hex_color": "#626D54", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Warm Grey", "paint_type": "base", "hex_color": "#939066", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Stonewall Grey", "paint_type": "base", "hex_color": "#828E95", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Blue Grey", "paint_type": "base", "hex_color": "#9CA7A7", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Steel Grey", "paint_type": "base", "hex_color": "#64889D", "category": "Grey", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Ghost Grey", "paint_type": "base", "hex_color": "#D9DAD9", "category": "Grey", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Bloody Red", "paint_type": "base", "hex_color": "#BF282E", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Scarlet Blood Red", "paint_type": "base", "hex_color": "#B72A38", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Red", "paint_type": "base", "hex_color": "#943238", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Hot Orange", "paint_type": "base", "hex_color": "#E43027", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Scarlet Red", "paint_type": "base", "hex_color": "#741330", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Gory Red", "paint_type": "base", "hex_color": "#8E1823", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Tan", "paint_type": "base", "hex_color": "#9F4746", "category": "Red", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Heavy Orange", "paint_type": "base", "hex_color": "#EE5527", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Orange Fire", "paint_type": "base", "hex_color": "#F1652E", "category": "Orange", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Filthy Brown", "paint_type": "base", "hex_color": "#F58D2B", "category": "Orange", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Sun Yellow", "paint_type": "base", "hex_color": "#FFCF07", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Moon Yellow", "paint_type": "base", "hex_color": "#FFF103", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Fluo Yellow", "paint_type": "base", "hex_color": "#EEEA50", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Pale Yellow", "paint_type": "base", "hex_color": "#D5C179", "category": "Yellow", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Plague Brown", "paint_type": "base", "hex_color": "#CC9B34", "category": "Yellow", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Beasty Brown", "paint_type": "base", "hex_color": "#55432D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Leather Brown", "paint_type": "base", "hex_color": "#7B5D2A", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Brown", "paint_type": "base", "hex_color": "#705D41", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Sienna", "paint_type": "base", "hex_color": "#744642", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Earth", "paint_type": "base", "hex_color": "#6F563D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Desert Yellow", "paint_type": "base", "hex_color": "#8E7845", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Gold Brown", "paint_type": "base", "hex_color": "#BA8636", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Ochre", "paint_type": "base", "hex_color": "#A87536", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Khaki", "paint_type": "base", "hex_color": "#9D965D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Khaki", "paint_type": "base", "hex_color": "#8C806D", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Dark Fleshtone", "paint_type": "base", "hex_color": "#4F2B26", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Terracotta", "paint_type": "base", "hex_color": "#B5683B", "category": "Brown", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Goblin Green", "paint_type": "base", "hex_color": "#23743C", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Green", "paint_type": "base", "hex_color": "#566840", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Mutation Green", "paint_type": "base", "hex_color": "#296934", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Scorpion Green", "paint_type": "base", "hex_color": "#48B851", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Sick Green", "paint_type": "base", "hex_color": "#096638", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Foul Green", "paint_type": "base", "hex_color": "#239378", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Jade Green", "paint_type": "base", "hex_color": "#128379", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Cayman Green", "paint_type": "base", "hex_color": "#285648", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Black Green", "paint_type": "base", "hex_color": "#18433D", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Scurvy Green", "paint_type": "base", "hex_color": "#09474E", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Camoflage Green", "paint_type": "base", "hex_color": "#71753A", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Yellow Olive", "paint_type": "base", "hex_color": "#063B2F", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Dead Flesh", "paint_type": "base", "hex_color": "#BCB686", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Verdigris", "paint_type": "base", "hex_color": "#B3CECA", "category": "Green", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Magic Blue", "paint_type": "base", "hex_color": "#024381", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Blue", "paint_type": "base", "hex_color": "#29556D", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Electric Blue", "paint_type": "base", "hex_color": "#008CBF", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Glacier Blue", "paint_type": "base", "hex_color": "#ACD0EE", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Royal Purple", "paint_type": "base", "hex_color": "#23264F", "category": "Blue", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Heavy Violet", "paint_type": "base", "hex_color": "#4C2E65", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Warlord Purple", "paint_type": "base", "hex_color": "#7D1A44", "category": "Purple", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Hexed Lichen", "paint_type": "base", "hex_color": "#5C3664", "category": "Purple", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Squid Pink", "paint_type": "base", "hex_color": "#DA7FB5", "category": "Pink", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Rosy Flesh", "paint_type": "base", "hex_color": "#F89E84", "category": "Pink", "is_custom": False},
    
    {"brand": "Vallejo Game Color", "name": "Elf Skintone", "paint_type": "base", "hex_color": "#E9C5A4", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Dwarf Skin", "paint_type": "base", "hex_color": "#CC7C67", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Heavy Skintone", "paint_type": "base", "hex_color": "#AA7B62", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Bronze Fleshtone", "paint_type": "base", "hex_color": "#DB945C", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Cadmium Skin", "paint_type": "base", "hex_color": "#FAB78A", "category": "Flesh", "is_custom": False},
    
    # Vallejo Game Color Metallics
    {"brand": "Vallejo Game Color", "name": "Polished Gold", "paint_type": "metallic", "hex_color": "#D4AF37", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Glorious Gold", "paint_type": "metallic", "hex_color": "#FFD700", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Chainmail Silver", "paint_type": "metallic", "hex_color": "#C0C0C0", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Bright Bronze", "paint_type": "metallic", "hex_color": "#CD7F32", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Hammered Copper", "paint_type": "metallic", "hex_color": "#B87333", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Tinny Tin", "paint_type": "metallic", "hex_color": "#8B8B83", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Gunmetal Blue", "paint_type": "metallic", "hex_color": "#4A4D4E", "category": "Metallic", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Brassy Brass", "paint_type": "metallic", "hex_color": "#C9AE5D", "category": "Metallic", "is_custom": False},
    
    # Vallejo Game Color Washes
    {"brand": "Vallejo Game Color", "name": "Black Wash", "paint_type": "wash", "hex_color": "#0A0A0A", "category": "Black", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Umber Wash", "paint_type": "wash", "hex_color": "#4A3728", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Sepia Wash", "paint_type": "wash", "hex_color": "#8B7355", "category": "Brown", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Green Wash", "paint_type": "wash", "hex_color": "#1A4028", "category": "Green", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Blue Wash", "paint_type": "wash", "hex_color": "#1A3050", "category": "Blue", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Red Wash", "paint_type": "wash", "hex_color": "#501A1A", "category": "Red", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Flesh Wash", "paint_type": "wash", "hex_color": "#5A4030", "category": "Flesh", "is_custom": False},
    {"brand": "Vallejo Game Color", "name": "Purple Wash", "paint_type": "wash", "hex_color": "#3A1A40", "category": "Purple", "is_custom": False},
]

ARMY_PAINTER_WARPAINTS = [
    # ========== ARMY PAINTER WARPAINTS FANATIC (100+ paints) ==========
    # Whites & Neutrals
    {"brand": "Army Painter", "name": "Matt White", "paint_type": "base", "hex_color": "#FFFFFF", "category": "White", "is_custom": False},
    {"brand": "Army Painter", "name": "Brainmatter Beige", "paint_type": "base", "hex_color": "#F1F0E0", "category": "White", "is_custom": False},
    {"brand": "Army Painter", "name": "Mummy Robes", "paint_type": "base", "hex_color": "#EBDED5", "category": "White", "is_custom": False},
    {"brand": "Army Painter", "name": "Corpse Pale", "paint_type": "base", "hex_color": "#EDCCAD", "category": "White", "is_custom": False},
    
    # Blacks & Greys
    {"brand": "Army Painter", "name": "Matt Black", "paint_type": "base", "hex_color": "#231F20", "category": "Black", "is_custom": False},
    {"brand": "Army Painter", "name": "Necromance Cloak", "paint_type": "base", "hex_color": "#3C3D37", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Dungeon Grey", "paint_type": "base", "hex_color": "#686C71", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Uniform Grey", "paint_type": "base", "hex_color": "#5E6A73", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Field Grey", "paint_type": "base", "hex_color": "#787C78", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Ash Grey", "paint_type": "base", "hex_color": "#A2A5A4", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Stone Golem", "paint_type": "base", "hex_color": "#B9BAB7", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Spaceship Exterior", "paint_type": "base", "hex_color": "#CDCED0", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Hardened Carapace", "paint_type": "base", "hex_color": "#4C473F", "category": "Grey", "is_custom": False},
    {"brand": "Army Painter", "name": "Crypt Wraith", "paint_type": "base", "hex_color": "#606050", "category": "Grey", "is_custom": False},
    
    # Reds
    {"brand": "Army Painter", "name": "Pure Red", "paint_type": "base", "hex_color": "#CF2127", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Mars Red", "paint_type": "base", "hex_color": "#B73B37", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Vampire Red", "paint_type": "base", "hex_color": "#981D34", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Dragon Red", "paint_type": "base", "hex_color": "#A01E21", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Crusted Sore", "paint_type": "base", "hex_color": "#611624", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Warlock Purple", "paint_type": "base", "hex_color": "#BB5B64", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Scar Tissue", "paint_type": "base", "hex_color": "#CA8772", "category": "Red", "is_custom": False},
    
    # Oranges
    {"brand": "Army Painter", "name": "Lava Orange", "paint_type": "base", "hex_color": "#E65525", "category": "Orange", "is_custom": False},
    {"brand": "Army Painter", "name": "Fire Lizard", "paint_type": "base", "hex_color": "#F37735", "category": "Orange", "is_custom": False},
    {"brand": "Army Painter", "name": "Phoenix Flames", "paint_type": "base", "hex_color": "#F58220", "category": "Orange", "is_custom": False},
    
    # Yellows
    {"brand": "Army Painter", "name": "Daemonic Yellow", "paint_type": "base", "hex_color": "#FADA06", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Babe Blonde", "paint_type": "base", "hex_color": "#F8DD0D", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Moon Dust", "paint_type": "base", "hex_color": "#E8D468", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Desert Yellow", "paint_type": "base", "hex_color": "#C7952C", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Sulfide Ochre", "paint_type": "base", "hex_color": "#C68512", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Poisonous Cloud", "paint_type": "base", "hex_color": "#CDDE4A", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter", "name": "Arid Earth", "paint_type": "base", "hex_color": "#FAECC3", "category": "Yellow", "is_custom": False},
    
    # Browns
    {"brand": "Army Painter", "name": "Leather Brown", "paint_type": "base", "hex_color": "#5E3A21", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Monster Brown", "paint_type": "base", "hex_color": "#855C2A", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Werewolf Fur", "paint_type": "base", "hex_color": "#785E4E", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Dirt Spatter", "paint_type": "base", "hex_color": "#5E3827", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Oak Brown", "paint_type": "base", "hex_color": "#432010", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Dark Stone", "paint_type": "base", "hex_color": "#605752", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Hemp Rope", "paint_type": "base", "hex_color": "#94763A", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Banshee Brown", "paint_type": "base", "hex_color": "#C3B097", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Filthy Cape", "paint_type": "base", "hex_color": "#7C7863", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Combat Fatigue", "paint_type": "base", "hex_color": "#878E5C", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Commando Green", "paint_type": "base", "hex_color": "#827B39", "category": "Brown", "is_custom": False},
    
    # Greens
    {"brand": "Army Painter", "name": "Greenskin", "paint_type": "base", "hex_color": "#136232", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Goblin Green", "paint_type": "base", "hex_color": "#348941", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Mouldy Clothes", "paint_type": "base", "hex_color": "#447B3A", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Army Green", "paint_type": "base", "hex_color": "#6E7645", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Snake Scales", "paint_type": "base", "hex_color": "#8AB239", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Scaly Hide", "paint_type": "base", "hex_color": "#859852", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Necrotic Flesh", "paint_type": "base", "hex_color": "#BFC292", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Kraken Skin", "paint_type": "base", "hex_color": "#71C591", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Elemental Bolt", "paint_type": "base", "hex_color": "#009A82", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Wizards Orb", "paint_type": "base", "hex_color": "#00726A", "category": "Green", "is_custom": False},
    
    # Blues
    {"brand": "Army Painter", "name": "Crystal Blue", "paint_type": "base", "hex_color": "#2F6B9A", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Deep Blue", "paint_type": "base", "hex_color": "#083251", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Griffon Blue", "paint_type": "base", "hex_color": "#215383", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Viking Blue", "paint_type": "base", "hex_color": "#00609A", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Electric Blue", "paint_type": "base", "hex_color": "#508CBE", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Voidshield Blue", "paint_type": "base", "hex_color": "#2CA2D9", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Troglodyte Blue", "paint_type": "base", "hex_color": "#0889BA", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Hydra Turquoise", "paint_type": "base", "hex_color": "#199BA3", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Royal Cloak", "paint_type": "base", "hex_color": "#15999C", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Wolf Grey", "paint_type": "base", "hex_color": "#5B8093", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Dark Sky", "paint_type": "base", "hex_color": "#2B4B5F", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Gorgon Hide", "paint_type": "base", "hex_color": "#C7D2E4", "category": "Blue", "is_custom": False},
    
    # Purples
    {"brand": "Army Painter", "name": "Alien Purple", "paint_type": "base", "hex_color": "#50317B", "category": "Purple", "is_custom": False},
    {"brand": "Army Painter", "name": "Wasteland Soil", "paint_type": "base", "hex_color": "#774B58", "category": "Purple", "is_custom": False},
    {"brand": "Army Painter", "name": "Grimoire Purple", "paint_type": "base", "hex_color": "#805259", "category": "Purple", "is_custom": False},
    
    # Pinks
    {"brand": "Army Painter", "name": "Pixie Pink", "paint_type": "base", "hex_color": "#D47A83", "category": "Pink", "is_custom": False},
    {"brand": "Army Painter", "name": "Centaur Skin", "paint_type": "base", "hex_color": "#DEABA0", "category": "Pink", "is_custom": False},
    
    # Flesh Tones
    {"brand": "Army Painter", "name": "Barbarian Flesh", "paint_type": "base", "hex_color": "#E89C6C", "category": "Flesh", "is_custom": False},
    {"brand": "Army Painter", "name": "Tanned Flesh", "paint_type": "base", "hex_color": "#BC745E", "category": "Flesh", "is_custom": False},
    {"brand": "Army Painter", "name": "Kobold Skin", "paint_type": "base", "hex_color": "#C9A484", "category": "Flesh", "is_custom": False},
    {"brand": "Army Painter", "name": "Troll Claws", "paint_type": "base", "hex_color": "#CB8B4E", "category": "Flesh", "is_custom": False},
    
    # Bones
    {"brand": "Army Painter", "name": "Skeleton Bone", "paint_type": "base", "hex_color": "#D3C89D", "category": "Bone", "is_custom": False},
    {"brand": "Army Painter", "name": "Drake Tooth", "paint_type": "base", "hex_color": "#CFCBB4", "category": "Bone", "is_custom": False},
    
    # Metallics
    {"brand": "Army Painter", "name": "Gun Metal", "paint_type": "metallic", "hex_color": "#4A4D4E", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "Shining Silver", "paint_type": "metallic", "hex_color": "#C3CACE", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "Plate Mail Metal", "paint_type": "metallic", "hex_color": "#8E9295", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "Greedy Gold", "paint_type": "metallic", "hex_color": "#B5803B", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "Weapon Bronze", "paint_type": "metallic", "hex_color": "#8C6239", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "Bright Gold", "paint_type": "metallic", "hex_color": "#D4AF37", "category": "Metallic", "is_custom": False},
    {"brand": "Army Painter", "name": "True Copper", "paint_type": "metallic", "hex_color": "#B87333", "category": "Metallic", "is_custom": False},
    
    # Washes/Quickshades
    {"brand": "Army Painter", "name": "Dark Tone", "paint_type": "shade", "hex_color": "#14100E", "category": "Black", "is_custom": False},
    {"brand": "Army Painter", "name": "Strong Tone", "paint_type": "shade", "hex_color": "#5A3D28", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Soft Tone", "paint_type": "shade", "hex_color": "#C28B5A", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter", "name": "Flesh Wash", "paint_type": "shade", "hex_color": "#5A2E28", "category": "Flesh", "is_custom": False},
    {"brand": "Army Painter", "name": "Blue Tone", "paint_type": "shade", "hex_color": "#12243E", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter", "name": "Green Tone", "paint_type": "shade", "hex_color": "#1A2E13", "category": "Green", "is_custom": False},
    {"brand": "Army Painter", "name": "Red Tone", "paint_type": "shade", "hex_color": "#510E15", "category": "Red", "is_custom": False},
    {"brand": "Army Painter", "name": "Purple Tone", "paint_type": "shade", "hex_color": "#2C1A35", "category": "Purple", "is_custom": False},
    
    # Speedpaints 2.0
    {"brand": "Army Painter Speedpaint", "name": "Grim Black", "paint_type": "speedpaint", "hex_color": "#1A1A1A", "category": "Black", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Absolution Green", "paint_type": "speedpaint", "hex_color": "#00401A", "category": "Green", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Blood Red", "paint_type": "speedpaint", "hex_color": "#9A1115", "category": "Red", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Highlord Blue", "paint_type": "speedpaint", "hex_color": "#0D407F", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Zealot Yellow", "paint_type": "speedpaint", "hex_color": "#FDB825", "category": "Yellow", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Pallid Bone", "paint_type": "speedpaint", "hex_color": "#DBD1B2", "category": "Bone", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Crusader Skin", "paint_type": "speedpaint", "hex_color": "#D1A570", "category": "Flesh", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Runic Purple", "paint_type": "speedpaint", "hex_color": "#3D3354", "category": "Purple", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Orc Skin", "paint_type": "speedpaint", "hex_color": "#677B4D", "category": "Green", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Hive Dweller", "paint_type": "speedpaint", "hex_color": "#5A3D28", "category": "Brown", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Holy White", "paint_type": "speedpaint", "hex_color": "#E5E5E5", "category": "White", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Slaughter Red", "paint_type": "speedpaint", "hex_color": "#C01411", "category": "Red", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Burning Bright", "paint_type": "speedpaint", "hex_color": "#F4874E", "category": "Orange", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Icy Blue", "paint_type": "speedpaint", "hex_color": "#7EC8E3", "category": "Blue", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Malignant Green", "paint_type": "speedpaint", "hex_color": "#1E7331", "category": "Green", "is_custom": False},
    {"brand": "Army Painter Speedpaint", "name": "Hardened Leather", "paint_type": "speedpaint", "hex_color": "#6C4811", "category": "Brown", "is_custom": False},
]

SCALE75_PAINTS = [
    # ========== SCALE75 FANTASY & GAMES + SCALECOLOR (40 paints) ==========
    {"brand": "Scale75", "name": "White", "paint_type": "base", "hex_color": "#FFFFFF", "category": "White", "is_custom": False},
    {"brand": "Scale75", "name": "Black", "paint_type": "base", "hex_color": "#000000", "category": "Black", "is_custom": False},
    {"brand": "Scale75", "name": "Graphite", "paint_type": "base", "hex_color": "#2D2D2D", "category": "Grey", "is_custom": False},
    {"brand": "Scale75", "name": "Anthracite Grey", "paint_type": "base", "hex_color": "#3D3D3D", "category": "Grey", "is_custom": False},
    {"brand": "Scale75", "name": "Rainy Grey", "paint_type": "base", "hex_color": "#6B6B6B", "category": "Grey", "is_custom": False},
    {"brand": "Scale75", "name": "Pale Grey", "paint_type": "base", "hex_color": "#9B9B9B", "category": "Grey", "is_custom": False},
    {"brand": "Scale75", "name": "Light Grey", "paint_type": "base", "hex_color": "#C8C8C8", "category": "Grey", "is_custom": False},
    
    {"brand": "Scale75", "name": "Antares Red", "paint_type": "base", "hex_color": "#891C11", "category": "Red", "is_custom": False},
    {"brand": "Scale75", "name": "Blood Red", "paint_type": "base", "hex_color": "#A91F16", "category": "Red", "is_custom": False},
    {"brand": "Scale75", "name": "Deep Red", "paint_type": "base", "hex_color": "#6B1610", "category": "Red", "is_custom": False},
    {"brand": "Scale75", "name": "Mars Orange", "paint_type": "base", "hex_color": "#E55522", "category": "Orange", "is_custom": False},
    {"brand": "Scale75", "name": "Sun Lizard", "paint_type": "base", "hex_color": "#F7941D", "category": "Orange", "is_custom": False},
    
    {"brand": "Scale75", "name": "Mojave Yellow", "paint_type": "base", "hex_color": "#D4A017", "category": "Yellow", "is_custom": False},
    {"brand": "Scale75", "name": "Sol Yellow", "paint_type": "base", "hex_color": "#FFD700", "category": "Yellow", "is_custom": False},
    {"brand": "Scale75", "name": "Sahara Yellow", "paint_type": "base", "hex_color": "#E5C87D", "category": "Yellow", "is_custom": False},
    
    {"brand": "Scale75", "name": "Bering Brown", "paint_type": "base", "hex_color": "#5C3D21", "category": "Brown", "is_custom": False},
    {"brand": "Scale75", "name": "Leather Brown", "paint_type": "base", "hex_color": "#7A5230", "category": "Brown", "is_custom": False},
    {"brand": "Scale75", "name": "Dubai Brown", "paint_type": "base", "hex_color": "#8B6914", "category": "Brown", "is_custom": False},
    {"brand": "Scale75", "name": "Sahara Dust", "paint_type": "base", "hex_color": "#BFA77A", "category": "Brown", "is_custom": False},
    {"brand": "Scale75", "name": "Nacar", "paint_type": "base", "hex_color": "#E8E4C9", "category": "Bone", "is_custom": False},
    {"brand": "Scale75", "name": "Birch", "paint_type": "base", "hex_color": "#D4C4A8", "category": "Flesh", "is_custom": False},
    
    {"brand": "Scale75", "name": "Sherwood Green", "paint_type": "base", "hex_color": "#2D5016", "category": "Green", "is_custom": False},
    {"brand": "Scale75", "name": "Irati Green", "paint_type": "base", "hex_color": "#4A7023", "category": "Green", "is_custom": False},
    {"brand": "Scale75", "name": "Viridian Green", "paint_type": "base", "hex_color": "#40826D", "category": "Green", "is_custom": False},
    {"brand": "Scale75", "name": "Caribbean Blue", "paint_type": "base", "hex_color": "#1A9D7B", "category": "Green", "is_custom": False},
    {"brand": "Scale75", "name": "Bering Sea", "paint_type": "base", "hex_color": "#0B4F4D", "category": "Green", "is_custom": False},
    
    {"brand": "Scale75", "name": "Innsmouth Blue", "paint_type": "base", "hex_color": "#1B4F72", "category": "Blue", "is_custom": False},
    {"brand": "Scale75", "name": "Navy Blue", "paint_type": "base", "hex_color": "#0D325B", "category": "Blue", "is_custom": False},
    {"brand": "Scale75", "name": "Cote d'Azur Blue", "paint_type": "base", "hex_color": "#2E79B5", "category": "Blue", "is_custom": False},
    {"brand": "Scale75", "name": "Adriatic Blue", "paint_type": "base", "hex_color": "#4A90D9", "category": "Blue", "is_custom": False},
    {"brand": "Scale75", "name": "Artic Blue", "paint_type": "base", "hex_color": "#7EC8E3", "category": "Blue", "is_custom": False},
    
    {"brand": "Scale75", "name": "Violet", "paint_type": "base", "hex_color": "#4B2D73", "category": "Purple", "is_custom": False},
    {"brand": "Scale75", "name": "Magenta", "paint_type": "base", "hex_color": "#9A2064", "category": "Purple", "is_custom": False},
    {"brand": "Scale75", "name": "Fuchsia", "paint_type": "base", "hex_color": "#C154C1", "category": "Pink", "is_custom": False},
    
    # Scale75 Metallics
    {"brand": "Scale75", "name": "Elven Gold", "paint_type": "metallic", "hex_color": "#C9A227", "category": "Metallic", "is_custom": False},
    {"brand": "Scale75", "name": "Viking Gold", "paint_type": "metallic", "hex_color": "#B87333", "category": "Metallic", "is_custom": False},
    {"brand": "Scale75", "name": "Thrash Metal", "paint_type": "metallic", "hex_color": "#7B7D7D", "category": "Metallic", "is_custom": False},
    {"brand": "Scale75", "name": "Decayed Metal", "paint_type": "metallic", "hex_color": "#5D6D7E", "category": "Metallic", "is_custom": False},
    {"brand": "Scale75", "name": "Speed Metal", "paint_type": "metallic", "hex_color": "#A8A9AD", "category": "Metallic", "is_custom": False},
    {"brand": "Scale75", "name": "Necro Gold", "paint_type": "metallic", "hex_color": "#A97C31", "category": "Metallic", "is_custom": False},
]

P3_FORMULA_PAINTS = [
    # ========== P3 FORMULA (Privateer Press - 50 paints) ==========
    {"brand": "P3", "name": "Morrow White", "paint_type": "base", "hex_color": "#FEFBFD", "category": "White", "is_custom": False},
    {"brand": "P3", "name": "Menoth White Base", "paint_type": "base", "hex_color": "#EFEFBB", "category": "White", "is_custom": False},
    {"brand": "P3", "name": "Menoth White Highlight", "paint_type": "base", "hex_color": "#F3F4DE", "category": "White", "is_custom": False},
    {"brand": "P3", "name": "Jack Bone", "paint_type": "base", "hex_color": "#D6D4AA", "category": "Bone", "is_custom": False},
    
    {"brand": "P3", "name": "Thamar Black", "paint_type": "base", "hex_color": "#040707", "category": "Black", "is_custom": False},
    {"brand": "P3", "name": "Cryx Bane Base", "paint_type": "base", "hex_color": "#303924", "category": "Grey", "is_custom": False},
    {"brand": "P3", "name": "Cryx Bane Highlight", "paint_type": "base", "hex_color": "#93907D", "category": "Grey", "is_custom": False},
    {"brand": "P3", "name": "Bastion Grey", "paint_type": "base", "hex_color": "#777965", "category": "Grey", "is_custom": False},
    {"brand": "P3", "name": "Greatcoat Grey", "paint_type": "base", "hex_color": "#4D5861", "category": "Grey", "is_custom": False},
    {"brand": "P3", "name": "Ironhull Grey", "paint_type": "base", "hex_color": "#8E969B", "category": "Grey", "is_custom": False},
    
    {"brand": "P3", "name": "Khador Red Base", "paint_type": "base", "hex_color": "#EE2824", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Khador Red Highlight", "paint_type": "base", "hex_color": "#F29042", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Skorne Red", "paint_type": "base", "hex_color": "#B01F24", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Sanguine Base", "paint_type": "base", "hex_color": "#6C160F", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Sanguine Highlight", "paint_type": "base", "hex_color": "#C84959", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Murderous Magenta", "paint_type": "base", "hex_color": "#A81F5E", "category": "Red", "is_custom": False},
    {"brand": "P3", "name": "Ember Orange", "paint_type": "base", "hex_color": "#DE8A2B", "category": "Orange", "is_custom": False},
    {"brand": "P3", "name": "Heartfire", "paint_type": "base", "hex_color": "#F6B046", "category": "Orange", "is_custom": False},
    
    {"brand": "P3", "name": "Cygnus Yellow", "paint_type": "base", "hex_color": "#F3E72E", "category": "Yellow", "is_custom": False},
    {"brand": "P3", "name": "Sulfuric Yellow", "paint_type": "base", "hex_color": "#F0D233", "category": "Yellow", "is_custom": False},
    {"brand": "P3", "name": "Hammerfall Khaki", "paint_type": "base", "hex_color": "#C8BF98", "category": "Yellow", "is_custom": False},
    {"brand": "P3", "name": "Rucksack Tan", "paint_type": "base", "hex_color": "#B4973F", "category": "Brown", "is_custom": False},
    
    {"brand": "P3", "name": "Battlefield Brown", "paint_type": "base", "hex_color": "#32251C", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Bootstrap Leather", "paint_type": "base", "hex_color": "#956939", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Gun Corps Brown", "paint_type": "base", "hex_color": "#937D48", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Beast Hide", "paint_type": "base", "hex_color": "#B1956B", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Thornwood Green", "paint_type": "base", "hex_color": "#65654B", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Bloodtracker Brown", "paint_type": "base", "hex_color": "#A66A28", "category": "Brown", "is_custom": False},
    {"brand": "P3", "name": "Bloodstone", "paint_type": "base", "hex_color": "#9E4822", "category": "Brown", "is_custom": False},
    
    {"brand": "P3", "name": "Gnarls Green", "paint_type": "base", "hex_color": "#126232", "category": "Green", "is_custom": False},
    {"brand": "P3", "name": "Iosan Green", "paint_type": "base", "hex_color": "#22A854", "category": "Green", "is_custom": False},
    {"brand": "P3", "name": "Necrotite Green", "paint_type": "base", "hex_color": "#7FC348", "category": "Green", "is_custom": False},
    {"brand": "P3", "name": "Ordic Olive", "paint_type": "base", "hex_color": "#6E7E36", "category": "Green", "is_custom": False},
    {"brand": "P3", "name": "Traitor Green", "paint_type": "base", "hex_color": "#809065", "category": "Green", "is_custom": False},
    {"brand": "P3", "name": "Coal Black", "paint_type": "base", "hex_color": "#005A61", "category": "Green", "is_custom": False},
    
    {"brand": "P3", "name": "Cygnar Blue Base", "paint_type": "base", "hex_color": "#124B9B", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Cygnar Blue Highlight", "paint_type": "base", "hex_color": "#1F75BB", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Exile Blue", "paint_type": "base", "hex_color": "#203367", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Trollblood Base", "paint_type": "base", "hex_color": "#13899B", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Trollblood Highlight", "paint_type": "base", "hex_color": "#BAB4A3", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Arcane Blue", "paint_type": "base", "hex_color": "#7ACFD9", "category": "Blue", "is_custom": False},
    {"brand": "P3", "name": "Underbelly Blue", "paint_type": "base", "hex_color": "#C0D4DA", "category": "Blue", "is_custom": False},
    
    {"brand": "P3", "name": "Beaten Purple", "paint_type": "base", "hex_color": "#552A72", "category": "Purple", "is_custom": False},
    
    {"brand": "P3", "name": "Midlund Flesh", "paint_type": "base", "hex_color": "#F0A983", "category": "Flesh", "is_custom": False},
    {"brand": "P3", "name": "Khardic Flesh", "paint_type": "base", "hex_color": "#CB7B5B", "category": "Flesh", "is_custom": False},
    {"brand": "P3", "name": "Idrian Flesh", "paint_type": "base", "hex_color": "#9B5E37", "category": "Flesh", "is_custom": False},
    {"brand": "P3", "name": "Ryn Flesh", "paint_type": "base", "hex_color": "#FAE3D1", "category": "Flesh", "is_custom": False},
    
    # P3 Metallics
    {"brand": "P3", "name": "Blighted Gold", "paint_type": "metallic", "hex_color": "#CFB53B", "category": "Metallic", "is_custom": False},
    {"brand": "P3", "name": "Brass Balls", "paint_type": "metallic", "hex_color": "#B5A642", "category": "Metallic", "is_custom": False},
    {"brand": "P3", "name": "Cold Steel", "paint_type": "metallic", "hex_color": "#A8A9AD", "category": "Metallic", "is_custom": False},
    {"brand": "P3", "name": "Quick Silver", "paint_type": "metallic", "hex_color": "#C0C0C0", "category": "Metallic", "is_custom": False},
    {"brand": "P3", "name": "Pig Iron", "paint_type": "metallic", "hex_color": "#5A5A5A", "category": "Metallic", "is_custom": False},
]
